### ISSUE TITLE
PHP 5.4 requirement

### ISSUE THREAD

**Issue by maxguru** [mikehaertl/php-shellcommand#52]
I am looking at #36 and #31. I might be missing something but is there any technical reason why 5.4 is required? I know we should all be on `7.4`, but maybe this requirement is arbitrary and `5.3` works just fine. The reason why I say this is php-pdftk requires this package but requires `5.3` or above, which is kind of strange.

**Comment by mikehaertl** [comment]
Don't remember exactly but I think it's because 5.4 is the lowest version we can test with travis using trusty. Other PHP versions may work - but we can't guarantee it as it's not tested. And honestly since the last PHP 5.3 release was 6 years ago (and the first even 11 years!) users can not expect too much support for it today.

But thanks for pointing out the mismatch to php-pdftk. I missed to bump the version to 5.4 there. Unless there's a good reason not to do so, I'll updated it there, too.

**Comment by maxguru** [comment]
I've tested this stuff on 5.3 a few years go and it was working. Some of my users are on 5.3 and it seems to be working fine.

**Comment by mikehaertl** [comment]
Like I said: It will probably work fine - it's just not "official". To skip the version check in composer you can use the `--ignore-platform-reqs` option.

**Comment by maxguru** [comment]
Thanks for all the great work you do!
