### ISSUE TITLE
setStdIn() doesn't work with useExec

### ISSUE THREAD

**Issue by maxguru** [mikehaertl/php-shellcommand#57]
[It looks like](https://github.com/mikehaertl/php-shellcommand/blob/3488d7803df1e8f1a343d3d0ca452d527ad8d5e5/src/Command.php#L371) `setStdIn()` doesn't work with `useExec`.

I propose the following method to allow `setStdIn()` to work with `useExec`, at least when `$this->_stdIn` is a string:
```
$tmp_file = tmpfile();
$tmp_path = stream_get_meta_data($tmp_file)['uri'];
fwrite($tmp_file, $this->_stdIn);
fflush($tmp_file);
$command = "cat ".escapeshellarg($tmp_path)." | $command";
...
fclose($tmp_file);
```

Using `cat` is a bit ugly, but maybe someone can come up with an improvement. Something similar can be done when `$this->_stdIn` is not a string.

**Comment by mikehaertl** [comment]
`useExec` was really just meant as a workaround if `proc_open()` does not work. It was never meant to be an alternative that supports all features.  Anything we do there to make it work would be rather hacky. In this case `cat` is probably not available on Windows systems (for mysterious reasons some really seem to develop with PHP there). 

If we enhance it I already see bug reports about other problems caused by this. Like hanging processes, which I found already unexpectedly hard to fix with `proc_open()` (see [here](https://github.com/mikehaertl/php-shellcommand/commit/290fc6c330bc84a8820350ef68ed975053e0823c#diff-faa401140cf85b1316c4fef76e8c33d48612bc213054ba64d6b7ba2ec70799a3R408)).

As I'm the poor guy who has to maintain this in the end I'd prefer if we leave `useExec` as it is to not even more encourage its use.

**Comment by maxguru** [comment]
Ok, I understand.

I do use this workaround myself (although without `cat`). A lot of Linux shared hosting servers have the `proc_*` functions disabled.

If you change your mind, I can send over a pull request.
